### ISSUE TITLE
[BUG] 100% CPU usage with idle cache

### ISSUE THREAD

**Issue by gzuidhof** [maypok86/otter#20] opened 2023-12-12 18:38 UTC
Thank you for this library @maypok86 

## Description

Creating a cache leads to one core being utilized at 100%. Creating multiple caches bumps this by one core at a time.

## To Reproduce

```go
package main

import "github.com/maypok86/otter"

// We assign this so that we're sure it doesn't get garbage collected
var Cache *otter.Cache[string, string]

func main() {
	b, err := otter.NewBuilder[string, string](1_000)
	if err != nil {
		panic(err)
	}

	c, err := b.Build()
	if err != nil {
		panic(err)
	}

	Cache = c

	// Block forever
	select {}
}
```

![Screenshot 2023-12-12 at 19 33 18](https://github.com/maypok86/otter/assets/1039510/e1de5aca-c027-4320-82ad-1406c2757d0e)

## Expected behavior

CPU usage is negligible.

## Environment

- OS: Both in Linux/Ubuntu and MacOS

## Additional context

I believe the issue lies in the goroutine spawned here https://github.com/maypok86/otter/blob/main/cache.go#L74

**Comment by maypok86** [comment] 2023-12-12 22:35
Thank you for the issue! It's actually a very nasty problem that is caused by this loop [here](https://github.com/maypok86/otter/blob/main/internal/queue/mpsc.go#L59). Since we can't do the same as standard channels (aka gopark and etc). For now, I just added checking for queue emptiness and sending goroutine to wait by standard channels without serious performance loss.

**Comment by maypok86** [comment] 2023-12-13 07:58
@gzuidhof I think I fixed the bug. However, it is still unclear how to write a test that would cover this bug. Please let me know if it's fixed for you too.

**Comment by maypok86** [comment] 2023-12-15 17:18
Okay, I can't reproduce this bug anymore, so I'll close this issue.

**Closed by maypok86** 2023-12-15 17:18 UTC
Labels: bug
